name: argon2
description: Pure Dart Argon2 algorithm (the winner of the Password Hash Competition 2015) for all Dart platforms (JS/Web, Flutter, VM/Native).
version: 1.0.0-no-null-safety
homepage: https://github.com/gmpassos/argon2

environment:
  sdk: '>=2.11.0 <3.0.0'

dependencies:
  pointycastle: ^2.0.1
  hex: ^0.1.2

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.1
  dependency_validator: ^3.1.0
